name: deploy to kubernetes (redis, kafka, zookeeper)

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl


      - name: Test Kubernetes Connection
        env:
          KUBE_SERVER: ${{ secrets.KUBE_SERVER }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}  
        run: |
          echo "Testing Kubernetes connection..."
          kubectl get nodes --server=$KUBE_SERVER --token=$KUBE_TOKEN --insecure-skip-tls-verify

      - name: Apply Kubernetes Configuration for Zookeeper, Kafka, and Redis
        env:
          KUBE_SERVER: ${{ secrets.KUBE_SERVER }}
          KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
        run: |
          echo "Applying Kubernetes configuration for Zookeeper, Kafka, and Redis..."
          
          # Zookeeper
          kubectl apply -f ./kubernetes/zookeeper_deployment.yaml --server=$KUBE_SERVER --token=$KUBE_TOKEN --insecure-skip-tls-verify --validate=false
          kubectl apply -f ./kubernetes/zookeeper_service.yaml --server=$KUBE_SERVER --token=$KUBE_TOKEN --insecure-skip-tls-verify --validate=false

          # Kafka
          kubectl apply -f ./kubernetes/kafka-statefulset.yaml --server=$KUBE_SERVER --token=$KUBE_TOKEN --insecure-skip-tls-verify --validate=false
          kubectl apply -f ./kubernetes/kafka_service.yaml --server=$KUBE_SERVER --token=$KUBE_TOKEN --insecure-skip-tls-verify --validate=false
          kubectl apply -f ./kubernetes/kafka-zookeeper-communication.yaml --server=$KUBE_SERVER --token=$KUBE_TOKEN --insecure-skip-tls-verify --validate=false

          # Redis
          kubectl apply -f ./kubernetes/redis-deployment.yaml --server=$KUBE_SERVER --token=$KUBE_TOKEN --insecure-skip-tls-verify --validate=false
          kubectl apply -f ./kubernetes/redis-service.yaml --server=$KUBE_SERVER --token=$KUBE_TOKEN --insecure-skip-tls-verify --validate=false
