name: deploy to kubernetes <redis> , <kafka> , <zookeeper> 

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: read

jobs:
  
  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      - name: Debug - Show secrets (only for debugging purposes, avoid exposing tokens in logs)
        env:
          KUBE_SERVER: ${{ secrets.KUBE_SERVER }}
          KUBE_TOKEN: ${{ env.KUBE_TOKEN }}
        run: |
          echo "KUBE_SERVER: $KUBE_SERVER"
          echo "KUBE_TOKEN: $KUBE_TOKEN"

      - name: Test Kubernetes Connection
        env:
          KUBE_SERVER: ${{ secrets.KUBE_SERVER }}
          KUBE_TOKEN: ${{ env.KUBE_TOKEN }}
        run: |
          echo "Testing Kubernetes connection..."
          kubectl get nodes --server=$KUBE_SERVER --token=$KUBE_TOKEN --insecure-skip-tls-verify
          
      - name: Apply Kubernetes Configuration
        env:
          KUBE_SERVER: ${{ secrets.KUBE_SERVER }}
          KUBE_TOKEN: ${{ env.KUBE_TOKEN }}
        run: |
          echo "Applying Kubernetes configuration..."
          kubectl apply -f ./kubernetes/zookeeper_deployment.yaml --server=$KUBE_SERVER --token=$KUBE_TOKEN --insecure-skip-tls-verify --validate=false
          kubectl apply -f ./kubernetes/zookeeper_service.yaml --server=$KUBE_SERVER --token=$KUBE_TOKEN --insecure-skip-tls-verify --validate=false
          kubectl apply -f ./kubernetes/kafka-statefulset.yaml --server=$KUBE_SERVER --token=$KUBE_TOKEN --insecure-skip-tls-verify --validate=false
          kubectl apply -f ./kubernetes/kafka_service.yaml --server=$KUBE_SERVER --token=$KUBE_TOKEN --insecure-skip-tls-verify --validate=false
          kubectl apply -f ./kubernetes/kafka-zookeeper-communication.yaml --server=$KUBE_SERVER --token=$KUBE_TOKEN --insecure-skip-tls-verify --validate=false
          kubectl apply -f ./kubernetes/redis-deployment.yaml --server=$KUBE_SERVER --token=$KUBE_TOKEN --insecure-skip-tls-verify --validate=false
          kubectl apply -f ./kubernetes/redis-service.yaml --server=$KUBE_SERVER --token=$KUBE_TOKEN --insecure-skip-tls-verify --validate=false
